const STORAGE_KEY = 'studywell-dashboard-v1';
const seed = {
  courses: [],
  assignments: []
};
let state = loadState();
const $ = (selector) => document.querySelector(selector);
const courseDialog = $('#courseDialog');
const assignmentDialog = $('#assignmentDialog');
const chatDialog = $('#chatDialog');

function loadState() {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(seed); }
  catch { return structuredClone(seed); }
}
function saveState(message = 'All changes saved locally') {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  $('#saveStatus').textContent = message;
  window.setTimeout(() => { $('#saveStatus').textContent = 'All changes saved locally'; }, 1800);
}
function uid(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 2400); }
function formatDate(value) { const date = new Date(`${value}T12:00:00`); return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }); }
function courseById(id) { return state.courses.find((course) => course.id === id); }
function isGradeEligible(assignment) { const today = new Date().toISOString().slice(0, 10); return assignment.status === 'done' || assignment.due < today; }
function hasGrade(assignment) { return assignment.earned !== '' && assignment.earned != null && Number(assignment.possible) > 0; }
function calculatedCourseGrade(course) { const gradedAssignments = state.assignments.filter((assignment) => assignment.courseId === course.id && hasGrade(assignment) && isGradeEligible(assignment)); if (!gradedAssignments.length) return Number(course.grade); return Math.round(gradedAssignments.reduce((sum, assignment) => sum + (Number(assignment.earned) / Number(assignment.possible) * 100), 0) / gradedAssignments.length); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function addChatMessage(message, author) { const bubble = document.createElement('div'); bubble.className = `chat-message ${author}`; bubble.textContent = message; $('#chatMessages').appendChild(bubble); $('#chatMessages').scrollTop = $('#chatMessages').scrollHeight; }
function answerStudyQuestion(question) { const normalizedQuestion = question.toLowerCase(); const activeAssignments = state.assignments.filter((assignment) => assignment.status !== 'done').sort((left, right) => left.due.localeCompare(right.due)); if (/gpa|grade|average/.test(normalizedQuestion)) { const gradedCourses = state.courses.filter((course) => state.assignments.some((assignment) => assignment.courseId === course.id && hasGrade(assignment) && isGradeEligible(assignment))); return gradedCourses.length ? `Your current assignment-based course grades are ${gradedCourses.map((course) => `${course.code}: ${calculatedCourseGrade(course)}%`).join(', ')}.` : 'Add earned and possible points to a completed or overdue assignment, and I can help you read the course average.'; } if (/what.*(do|next)|where.*start|priorit|urgent|today/.test(normalizedQuestion)) { return activeAssignments.length ? `Start with ${activeAssignments[0].name}. It is due ${formatDate(activeAssignments[0].due)} and has ${activeAssignments[0].duration || 45} minutes planned.` : 'You are clear for now. Add an assignment when your next task is ready.'; } if (/plan|schedule|organize|time/.test(normalizedQuestion)) return 'Pick one small goal, set a focused time block, then take a five-minute break. For a larger task, split it into 25-minute blocks and stop after each block to check your progress.'; if (/memor|remember|flashcard|study/.test(normalizedQuestion)) return 'Use active recall: close your notes, write what you remember, then check your gaps. Turn the gaps into a few flashcards and review them again tomorrow.'; if (/essay|write|paper/.test(normalizedQuestion)) return 'Start with a rough thesis, list three supporting points, and write an imperfect first draft. Leave polishing and citations for a separate pass.'; if (/math|problem|equation|calculate/.test(normalizedQuestion)) return 'Work one example without looking at the solution, explain why each step works, then try a similar problem with different numbers.'; return 'I can help with study strategies, planning, memory techniques, writing, basic problem solving, and reading your saved grades. What are you working on?'; }
function plannerContext() { return state.assignments.length ? `Courses: ${state.courses.map((course) => `${course.code} (${calculatedCourseGrade(course)}%)`).join(', ')}. Assignments: ${state.assignments.map((assignment) => `${assignment.name} (${assignment.status}, due ${assignment.due})`).join('; ')}.` : 'The student has no assignments or courses saved yet.'; }
async function askOllama(question) { const model = $('#ollamaModel').value.trim() || 'llama3.2'; const response = await fetch('http://localhost:11434/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model, stream: false, messages: [{ role: 'system', content: 'You are a concise, encouraging study assistant. Answer basic study questions clearly in under 120 words. Use this planner context when relevant: ' + plannerContext() }, { role: 'user', content: question }] }) }); if (!response.ok) throw new Error(`Ollama returned ${response.status}`); const data = await response.json(); if (!data.message?.content) throw new Error('Ollama returned no message'); return data.message.content.trim(); }

function render() {
  renderCourses(); renderAssignments(); renderCourseOptions(); updateSummary();
}
function renderCourses() {
  const list = $('#courseList');
  if (!state.courses.length) { list.innerHTML = '<div class="empty-state">Add your first course to get started.</div>'; return; }
  list.innerHTML = state.courses.map((course) => { const grade = calculatedCourseGrade(course); const hasGradedAssignments = state.assignments.some((assignment) => assignment.courseId === course.id && hasGrade(assignment) && isGradeEligible(assignment)); return `<article class="course-card"><div class="course-title"><span class="course-dot ${course.accent}"></span><div><div class="course-name">${escapeHtml(course.name)}</div><div class="course-code">${escapeHtml(course.code)}</div></div></div><div><div class="progress-track"><div class="progress-fill" style="width:${grade}%"></div></div><div class="course-grade">${grade}% <small>${hasGradedAssignments ? 'assignment average' : 'current grade'}</small></div></div><div class="course-actions"><button class="course-menu" type="button" data-edit-course="${course.id}" aria-label="Edit ${escapeHtml(course.name)}">✎</button><button class="course-menu" type="button" data-delete-course="${course.id}" aria-label="Delete ${escapeHtml(course.name)}">×</button></div></article>`; }).join('');
}
function renderAssignments() {
  const filter = $('#courseFilter').value; const list = $('#assignmentList');
  const assignments = state.assignments.filter((assignment) => filter === 'all' || assignment.courseId === filter);
  $('#emptyAssignments').hidden = assignments.length > 0;
  const today = new Date().toISOString().slice(0, 10);
  list.innerHTML = assignments.map((assignment) => { const course = courseById(assignment.courseId); const overdue = assignment.due < today && assignment.status !== 'done'; const grade = assignment.earned !== '' && assignment.earned != null && assignment.possible ? `${assignment.earned}/${assignment.possible}` : '—'; return `<tr><td>${escapeHtml(assignment.name)}</td><td class="assignment-course">${course ? escapeHtml(course.code) : 'Unassigned'}</td><td class="date ${overdue ? 'overdue' : assignment.priority === 'high' && assignment.status !== 'done' ? 'soon' : ''}">${formatDate(assignment.due)}${overdue ? '<small class="overdue-label">Overdue</small>' : ''}</td><td class="date">${assignment.duration || 45} min</td><td class="date assignment-grade">${grade}</td><td><button class="pill ${assignment.priority} priority-button" type="button" data-priority-id="${assignment.id}" title="Change priority" aria-label="Change priority for ${escapeHtml(assignment.name)}">${assignment.priority}</button></td><td><select class="status-select ${assignment.status}" data-status-id="${assignment.id}" aria-label="Change status for ${escapeHtml(assignment.name)}"><option value="todo" ${assignment.status === 'todo' ? 'selected' : ''}>To do</option><option value="in-progress" ${assignment.status === 'in-progress' ? 'selected' : ''}>In progress</option><option value="done" ${assignment.status === 'done' ? 'selected' : ''}>Complete</option></select></td><td class="row-actions"><button class="icon-button" type="button" data-edit-assignment="${assignment.id}" aria-label="Edit ${escapeHtml(assignment.name)}">✎</button><button class="icon-button" type="button" data-delete-assignment="${assignment.id}" aria-label="Delete ${escapeHtml(assignment.name)}">×</button></td></tr>`; }).join('');
}
function renderCourseOptions() { const options = state.courses.map((course) => `<option value="${course.id}">${escapeHtml(course.code)} · ${escapeHtml(course.name)}</option>`).join(''); $('#courseFilter').innerHTML = '<option value="all">All courses</option>' + options; if (!state.courses.length) $('#assignmentCourse').innerHTML = '<option value="">Add a course first</option>'; else $('#assignmentCourse').innerHTML = options; }
function updateSummary() { const active = state.assignments.filter((assignment) => assignment.status !== 'done'); const today = new Date().toISOString().slice(0, 10); const overdue = active.filter((assignment) => assignment.due < today); const completed = state.assignments.filter((assignment) => assignment.status === 'done'); const average = state.courses.length ? Math.round(state.courses.reduce((sum, course) => sum + calculatedCourseGrade(course), 0) / state.courses.length) : 0; $('#gpaValue').textContent = state.courses.length ? (average / 25).toFixed(2) : '0.00'; $('#dueValue').textContent = String(active.length).padStart(2, '0'); $('#urgentValue').textContent = String(active.filter((assignment) => assignment.priority === 'high').length); $('#overdueValue').textContent = String(overdue.length).padStart(2, '0'); $('#overdueLabel').textContent = overdue.length ? `${overdue.length === 1 ? 'Needs' : 'Need'} attention` : 'No overdue work'; $('#completedValue').textContent = String(completed.length).padStart(2, '0'); $('#totalAssignmentsValue').textContent = String(state.assignments.length).padStart(2, '0'); renderTodayFocus(active); }
function renderTodayFocus(active) { const today = new Date().toISOString().slice(0, 10); const priorityOrder = { high: 0, medium: 1, low: 2 }; const todayAssignments = active.filter((assignment) => assignment.due === today).sort((left, right) => (priorityOrder[left.priority] - priorityOrder[right.priority]) || left.name.localeCompare(right.name)); const orderedAssignments = todayAssignments.length ? todayAssignments : active.slice().sort((left, right) => left.due.localeCompare(right.due) || (priorityOrder[left.priority] - priorityOrder[right.priority])); $('#todayFocusList').innerHTML = orderedAssignments.length ? orderedAssignments.map((assignment, index) => `<div class="focus-task"><span>${index + 1}</span><strong>${escapeHtml(assignment.name)}</strong><small>${assignment.duration || 45} min</small></div>`).join('') : '<div class="focus-task"><strong>No tasks due today</strong></div>'; }

function openCourse(course) { $('#courseDialogTitle').textContent = course ? 'Edit course' : 'Add a course'; $('#courseId').value = course?.id || ''; $('#courseName').value = course?.name || ''; $('#courseCode').value = course?.code || ''; $('#courseGrade').value = course?.grade ?? 90; document.querySelector(`input[name="courseAccent"][value="${course?.accent || 'orange'}"]`).checked = true; courseDialog.showModal(); $('#courseName').focus(); }
function openAssignment(assignment) { $('#assignmentDialogTitle').textContent = assignment ? 'Edit assignment' : 'Add an assignment'; $('#assignmentId').value = assignment?.id || ''; $('#assignmentName').value = assignment?.name || ''; $('#assignmentCourse').value = assignment?.courseId || state.courses[0]?.id || ''; $('#assignmentDue').value = assignment?.due || new Date().toISOString().slice(0, 10); $('#assignmentDuration').value = assignment?.duration || '45'; $('#assignmentPriority').value = assignment?.priority || 'medium'; $('#assignmentEarned').value = assignment?.earned ?? ''; $('#assignmentPossible').value = assignment?.possible ?? ''; $('#assignmentStatus').value = assignment?.status || 'todo'; assignmentDialog.showModal(); $('#assignmentName').focus(); }

$('#addCourseButton').addEventListener('click', () => openCourse());
$('#quickAddButton').addEventListener('click', () => openAssignment());
$('#addAssignmentButton').addEventListener('click', () => state.courses.length ? openAssignment() : (openCourse(), showToast('Add a course before planning an assignment')));
document.querySelectorAll('[data-close-dialog]').forEach((button) => button.addEventListener('click', () => document.getElementById(button.dataset.closeDialog).close()));
$('#askStudyButton').addEventListener('click', () => { chatDialog.showModal(); if (!$('#chatMessages').children.length) addChatMessage('Hi. Ask me a basic study question, or ask what to work on next.', 'assistant'); $('#chatInput').focus(); });
$('#chatForm').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('#chatInput'); const sendButton = $('#chatForm button[type="submit"]'); const question = input.value.trim(); if (!question) return; addChatMessage(question, 'user'); input.value = ''; input.disabled = true; sendButton.disabled = true; sendButton.textContent = '...'; try { addChatMessage(await askOllama(question), 'assistant'); } catch (error) { addChatMessage(`${answerStudyQuestion(question)}\n\n(Ollama is unavailable, so I used the offline helper. Start Ollama and make sure the model “${$('#ollamaModel').value.trim() || 'llama3.2'}” is installed to use the local AI.)`, 'assistant'); } finally { input.disabled = false; sendButton.disabled = false; sendButton.textContent = 'Send'; input.focus(); } });
$('#clearChatButton').addEventListener('click', () => { $('#chatMessages').replaceChildren(); addChatMessage('Hi. Ask me a basic study question, or ask what to work on next.', 'assistant'); });
$('#courseFilter').addEventListener('change', renderAssignments);
$('#courseList').addEventListener('click', (event) => { const button = event.target.closest('[data-edit-course]'); const remove = event.target.closest('[data-delete-course]'); if (button) openCourse(courseById(button.dataset.editCourse)); if (remove) { const course = courseById(remove.dataset.deleteCourse); if (!course || !window.confirm(`Delete ${course.name}? Its assignments will also be removed.`)) return; state.courses = state.courses.filter((item) => item.id !== course.id); state.assignments = state.assignments.filter((item) => item.courseId !== course.id); saveState('Course deleted'); render(); showToast('Course deleted'); } });
$('#assignmentList').addEventListener('click', (event) => { const edit = event.target.closest('[data-edit-assignment]'); const remove = event.target.closest('[data-delete-assignment]'); if (edit) openAssignment(state.assignments.find((assignment) => assignment.id === edit.dataset.editAssignment)); if (remove) { state.assignments = state.assignments.filter((assignment) => assignment.id !== remove.dataset.deleteAssignment); saveState('Assignment deleted'); render(); showToast('Assignment deleted'); } });
$('#assignmentList').addEventListener('click', (event) => { const priorityButton = event.target.closest('[data-priority-id]'); if (!priorityButton) return; const assignment = state.assignments.find((item) => item.id === priorityButton.dataset.priorityId); const priorities = ['low', 'medium', 'high']; assignment.priority = priorities[(priorities.indexOf(assignment.priority) + 1) % priorities.length]; saveState('Priority updated'); render(); showToast(`Priority set to ${assignment.priority}`); });
$('#assignmentList').addEventListener('change', (event) => { const select = event.target.closest('[data-status-id]'); if (select) { const assignment = state.assignments.find((item) => item.id === select.dataset.statusId); assignment.status = select.value; saveState('Status updated'); render(); showToast('Status updated'); } });
$('#courseForm').addEventListener('submit', (event) => { event.preventDefault(); const id = $('#courseId').value; const course = { id: id || uid('course'), name: $('#courseName').value.trim(), code: $('#courseCode').value.trim(), grade: Number($('#courseGrade').value), accent: document.querySelector('input[name="courseAccent"]:checked').value }; if (id) state.courses = state.courses.map((item) => item.id === id ? course : item); else state.courses.push(course); saveState(id ? 'Course updated' : 'Course added'); courseDialog.close(); render(); showToast(id ? 'Course updated' : 'Course added'); });
$('#assignmentForm').addEventListener('submit', (event) => { event.preventDefault(); const id = $('#assignmentId').value; const earned = $('#assignmentEarned').value; const possible = $('#assignmentPossible').value; const assignment = { id: id || uid('assignment'), name: $('#assignmentName').value.trim(), courseId: $('#assignmentCourse').value, due: $('#assignmentDue').value, duration: Number($('#assignmentDuration').value), priority: $('#assignmentPriority').value, earned, possible, status: $('#assignmentStatus').value }; if (id) state.assignments = state.assignments.map((item) => item.id === id ? assignment : item); else state.assignments.push(assignment); saveState(id ? 'Assignment updated' : 'Assignment added'); assignmentDialog.close(); render(); showToast(id ? 'Assignment updated' : 'Assignment added'); });

render();
