const STORAGE_KEY = 'studywell-dashboard-v1';
const seed = {
  courses: [],
  assignments: []
};
let state = loadState();
const $ = (selector) => document.querySelector(selector);
const courseDialog = $('#courseDialog');
const assignmentDialog = $('#assignmentDialog');

function loadState() {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(seed); }
  catch { return structuredClone(seed); }
}
function saveState(message = 'All changes saved locally') {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  $('#saveStatus').textContent = message;
  window.setTimeout(() => { $('#saveStatus').textContent = 'All changes saved locally'; }, 1800);
}
function uid(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 2400); }
function formatDate(value) { const date = new Date(`${value}T12:00:00`); return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }); }
function courseById(id) { return state.courses.find((course) => course.id === id); }
function isGradeEligible(assignment) { const today = new Date().toISOString().slice(0, 10); return assignment.status === 'done' || assignment.due < today; }
function hasGrade(assignment) { return assignment.earned !== '' && assignment.earned != null && Number(assignment.possible) > 0; }
function calculatedCourseGrade(course) { const gradedAssignments = state.assignments.filter((assignment) => assignment.courseId === course.id && hasGrade(assignment) && isGradeEligible(assignment)); if (!gradedAssignments.length) return Number(course.grade); return Math.round(gradedAssignments.reduce((sum, assignment) => sum + (Number(assignment.earned) / Number(assignment.possible) * 100), 0) / gradedAssignments.length); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }

function render() {
  renderCourses(); renderAssignments(); renderCourseOptions(); updateSummary();
}
function renderCourses() {
  const list = $('#courseList');
  if (!state.courses.length) { list.innerHTML = '<div class="empty-state">Add your first course to get started.</div>'; return; }
  list.innerHTML = state.courses.map((course) => { const grade = calculatedCourseGrade(course); const hasGradedAssignments = state.assignments.some((assignment) => assignment.courseId === course.id && hasGrade(assignment) && isGradeEligible(assignment)); return `<article class="course-card"><div class="course-title"><span class="course-dot ${course.accent}"></span><div><div class="course-name">${escapeHtml(course.name)}</div><div class="course-code">${escapeHtml(course.code)}</div></div></div><div><div class="progress-track"><div class="progress-fill" style="width:${grade}%"></div></div><div class="course-grade">${grade}% <small>${hasGradedAssignments ? 'assignment average' : 'current grade'}</small></div></div><div class="course-actions"><button class="course-menu" type="button" data-edit-course="${course.id}" aria-label="Edit ${escapeHtml(course.name)}">✎</button><button class="course-menu" type="button" data-delete-course="${course.id}" aria-label="Delete ${escapeHtml(course.name)}">×</button></div></article>`; }).join('');
}
function renderAssignments() {
  const filter = $('#courseFilter').value; const list = $('#assignmentList');
  const assignments = state.assignments.filter((assignment) => filter === 'all' || assignment.courseId === filter);
  $('#emptyAssignments').hidden = assignments.length > 0;
  const today = new Date().toISOString().slice(0, 10);
  list.innerHTML = assignments.map((assignment) => { const course = courseById(assignment.courseId); const overdue = assignment.due < today && assignment.status !== 'done'; const grade = assignment.earned !== '' && assignment.earned != null && assignment.possible ? `${assignment.earned}/${assignment.possible}` : '—'; return `<tr><td>${escapeHtml(assignment.name)}</td><td class="assignment-course">${course ? escapeHtml(course.code) : 'Unassigned'}</td><td class="date ${overdue ? 'overdue' : assignment.priority === 'high' && assignment.status !== 'done' ? 'soon' : ''}">${formatDate(assignment.due)}${overdue ? '<small class="overdue-label">Overdue</small>' : ''}</td><td class="date">${assignment.duration || 45} min</td><td class="date assignment-grade">${grade}</td><td><button class="pill ${assignment.priority} priority-button" type="button" data-priority-id="${assignment.id}" title="Change priority" aria-label="Change priority for ${escapeHtml(assignment.name)}">${assignment.priority}</button></td><td><select class="status-select ${assignment.status}" data-status-id="${assignment.id}" aria-label="Change status for ${escapeHtml(assignment.name)}"><option value="todo" ${assignment.status === 'todo' ? 'selected' : ''}>To do</option><option value="in-progress" ${assignment.status === 'in-progress' ? 'selected' : ''}>In progress</option><option value="done" ${assignment.status === 'done' ? 'selected' : ''}>Complete</option></select></td><td class="row-actions"><button class="icon-button" type="button" data-edit-assignment="${assignment.id}" aria-label="Edit ${escapeHtml(assignment.name)}">✎</button><button class="icon-button" type="button" data-delete-assignment="${assignment.id}" aria-label="Delete ${escapeHtml(assignment.name)}">×</button></td></tr>`; }).join('');
}
function renderCourseOptions() { const options = state.courses.map((course) => `<option value="${course.id}">${escapeHtml(course.code)} · ${escapeHtml(course.name)}</option>`).join(''); $('#courseFilter').innerHTML = '<option value="all">All courses</option>' + options; if (!state.courses.length) $('#assignmentCourse').innerHTML = '<option value="">Add a course first</option>'; else $('#assignmentCourse').innerHTML = options; }
function updateSummary() { const active = state.assignments.filter((assignment) => assignment.status !== 'done'); const average = state.courses.length ? Math.round(state.courses.reduce((sum, course) => sum + calculatedCourseGrade(course), 0) / state.courses.length) : 0; $('#gpaValue').textContent = state.courses.length ? (average / 25).toFixed(2) : '0.00'; $('#dueValue').textContent = String(active.length).padStart(2, '0'); $('#urgentValue').textContent = String(active.filter((assignment) => assignment.priority === 'high').length); renderTodayFocus(active); }
function renderTodayFocus(active) { const today = new Date().toISOString().slice(0, 10); const priorityOrder = { high: 0, medium: 1, low: 2 }; const todayAssignments = active.filter((assignment) => assignment.due === today).sort((left, right) => (priorityOrder[left.priority] - priorityOrder[right.priority]) || left.name.localeCompare(right.name)); const orderedAssignments = todayAssignments.length ? todayAssignments : active.slice().sort((left, right) => left.due.localeCompare(right.due) || (priorityOrder[left.priority] - priorityOrder[right.priority])); $('#todayFocusList').innerHTML = orderedAssignments.length ? orderedAssignments.map((assignment, index) => `<div class="focus-task"><span>${index + 1}</span><strong>${escapeHtml(assignment.name)}</strong><small>${assignment.duration || 45} min</small></div>`).join('') : '<div class="focus-task"><strong>No tasks due today</strong></div>'; }

function openCourse(course) { $('#courseDialogTitle').textContent = course ? 'Edit course' : 'Add a course'; $('#courseId').value = course?.id || ''; $('#courseName').value = course?.name || ''; $('#courseCode').value = course?.code || ''; $('#courseGrade').value = course?.grade ?? 90; document.querySelector(`input[name="courseAccent"][value="${course?.accent || 'orange'}"]`).checked = true; courseDialog.showModal(); $('#courseName').focus(); }
function openAssignment(assignment) { $('#assignmentDialogTitle').textContent = assignment ? 'Edit assignment' : 'Add an assignment'; $('#assignmentId').value = assignment?.id || ''; $('#assignmentName').value = assignment?.name || ''; $('#assignmentCourse').value = assignment?.courseId || state.courses[0]?.id || ''; $('#assignmentDue').value = assignment?.due || new Date().toISOString().slice(0, 10); $('#assignmentDuration').value = assignment?.duration || '45'; $('#assignmentPriority').value = assignment?.priority || 'medium'; $('#assignmentEarned').value = assignment?.earned ?? ''; $('#assignmentPossible').value = assignment?.possible ?? ''; $('#assignmentStatus').value = assignment?.status || 'todo'; assignmentDialog.showModal(); $('#assignmentName').focus(); }

$('#addCourseButton').addEventListener('click', () => openCourse());
$('#quickAddButton').addEventListener('click', () => openAssignment());
$('#addAssignmentButton').addEventListener('click', () => state.courses.length ? openAssignment() : (openCourse(), showToast('Add a course before planning an assignment')));
document.querySelectorAll('[data-close-dialog]').forEach((button) => button.addEventListener('click', () => document.getElementById(button.dataset.closeDialog).close()));
$('#courseFilter').addEventListener('change', renderAssignments);
$('#courseList').addEventListener('click', (event) => { const button = event.target.closest('[data-edit-course]'); const remove = event.target.closest('[data-delete-course]'); if (button) openCourse(courseById(button.dataset.editCourse)); if (remove) { const course = courseById(remove.dataset.deleteCourse); if (!course || !window.confirm(`Delete ${course.name}? Its assignments will also be removed.`)) return; state.courses = state.courses.filter((item) => item.id !== course.id); state.assignments = state.assignments.filter((item) => item.courseId !== course.id); saveState('Course deleted'); render(); showToast('Course deleted'); } });
$('#assignmentList').addEventListener('click', (event) => { const edit = event.target.closest('[data-edit-assignment]'); const remove = event.target.closest('[data-delete-assignment]'); if (edit) openAssignment(state.assignments.find((assignment) => assignment.id === edit.dataset.editAssignment)); if (remove) { state.assignments = state.assignments.filter((assignment) => assignment.id !== remove.dataset.deleteAssignment); saveState('Assignment deleted'); render(); showToast('Assignment deleted'); } });
$('#assignmentList').addEventListener('click', (event) => { const priorityButton = event.target.closest('[data-priority-id]'); if (!priorityButton) return; const assignment = state.assignments.find((item) => item.id === priorityButton.dataset.priorityId); const priorities = ['low', 'medium', 'high']; assignment.priority = priorities[(priorities.indexOf(assignment.priority) + 1) % priorities.length]; saveState('Priority updated'); render(); showToast(`Priority set to ${assignment.priority}`); });
$('#assignmentList').addEventListener('change', (event) => { const select = event.target.closest('[data-status-id]'); if (select) { const assignment = state.assignments.find((item) => item.id === select.dataset.statusId); assignment.status = select.value; saveState('Status updated'); render(); showToast('Status updated'); } });
$('#courseForm').addEventListener('submit', (event) => { event.preventDefault(); const id = $('#courseId').value; const course = { id: id || uid('course'), name: $('#courseName').value.trim(), code: $('#courseCode').value.trim(), grade: Number($('#courseGrade').value), accent: document.querySelector('input[name="courseAccent"]:checked').value }; if (id) state.courses = state.courses.map((item) => item.id === id ? course : item); else state.courses.push(course); saveState(id ? 'Course updated' : 'Course added'); courseDialog.close(); render(); showToast(id ? 'Course updated' : 'Course added'); });
$('#assignmentForm').addEventListener('submit', (event) => { event.preventDefault(); const id = $('#assignmentId').value; const earned = $('#assignmentEarned').value; const possible = $('#assignmentPossible').value; const assignment = { id: id || uid('assignment'), name: $('#assignmentName').value.trim(), courseId: $('#assignmentCourse').value, due: $('#assignmentDue').value, duration: Number($('#assignmentDuration').value), priority: $('#assignmentPriority').value, earned, possible, status: $('#assignmentStatus').value }; if (id) state.assignments = state.assignments.map((item) => item.id === id ? assignment : item); else state.assignments.push(assignment); saveState(id ? 'Assignment updated' : 'Assignment added'); assignmentDialog.close(); render(); showToast(id ? 'Assignment updated' : 'Assignment added'); });

render();
